<a href="https://colab.research.google.com/github/MrckHckr/iss-digital-twin/blob/main/01_ISS_Simulator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

n = 10000

df = pd.DataFrame({
    "temperature": np.random.normal(22,2,n),
    "power_usage": np.random.normal(120,15,n),
    "battery_level": np.random.normal(90,5,n),
    "vibration": np.random.normal(0.02,0.005,n)
})

df.head()

   temperature  power_usage  battery_level  vibration
0    21.588015   126.303881      89.654860   0.014623
1    20.650998   134.796108      93.356166   0.018106
2    24.255164   123.529301      90.882108   0.017757
3    24.214327   137.987936      85.678563   0.019246
4    24.093014   114.437137      87.262732   0.014307

In [2]:
modules = [
    "Node1",
    "Node2",
    "Harmony",
    "Columbus",
    "Kibo",
    "Cupola"
]

In [3]:
iss_modules = pd.DataFrame({
    "module": modules,
    "health_score": [100]*6,
    "temperature": np.random.normal(22,1,6),
    "power_usage": np.random.normal(120,10,6),
    "battery_level": np.random.normal(95,2,6)
})

iss_modules

     module  health_score  temperature  power_usage  battery_level
0     Node1           100    21.720772   126.175147      94.948712
1     Node2           100    23.192624   139.971089      94.770315
2   Harmony           100    22.029002   102.610491      92.059698
3  Columbus           100    22.092627   127.189219      91.659378
4      Kibo           100    21.977040   124.662170      94.201833
5    Cupola           100    22.421406   128.311661      95.367523

In [4]:
iss_modules["temperature"] += np.random.normal(0,0.2,6)
iss_modules["power_usage"] += np.random.normal(0,1,6)

iss_modules

     module  health_score  temperature  power_usage  battery_level
0     Node1           100    21.807742   126.577097      94.948712
1     Node2           100    23.163651   139.813956      94.770315
2   Harmony           100    22.427018   102.818114      92.059698
3  Columbus           100    22.078657   127.255933      91.659378
4      Kibo           100    22.078368   124.131114      94.201833
5    Cupola           100    22.446923   127.749806      95.367523