<a href="https://colab.research.google.com/github/MrckHckr/iss-digital-twin/blob/main/notebooks/03_Anomaly_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest

import plotly.express as px

In [2]:
n = 10000

df = pd.DataFrame({
    "temperature": np.random.normal(22,2,n),
    "power_usage": np.random.normal(120,15,n),
    "battery_level": np.random.normal(90,5,n),
    "vibration": np.random.normal(0.02,0.005,n)
})

In [3]:
anomaly_indices = np.random.choice(
    df.index,
    size=100,
    replace=False
)

df.loc[anomaly_indices,"temperature"] = np.random.uniform(35,50,100)

df.loc[anomaly_indices,"vibration"] = np.random.uniform(0.05,0.10,100)

In [4]:
features = [
    "temperature",
    "power_usage",
    "battery_level",
    "vibration"
]

model = IsolationForest(
    contamination=0.01,
    random_state=42
)

model.fit(df[features])

IsolationForest(contamination=0.01, random_state=42)

In [5]:
df["anomaly"] = model.predict(df[features])

In [6]:
df["anomaly"] = df["anomaly"].map({
    1:0,
    -1:1
})

In [7]:
df["anomaly"].value_counts()

anomaly
0    9900
1     100
Name: count, dtype: int64

In [8]:
fig = px.scatter(
    df,
    x="temperature",
    y="vibration",
    color="anomaly",
    title="ISS Anomaly Detection"
)

fig.show()

In [9]:
anomalies = df[df["anomaly"] == 1]

anomalies.head(20)

      temperature  power_usage  battery_level  vibration  anomaly
38      36.803625   126.303554      96.239821   0.098308        1
228     45.118187    85.509733      80.990708   0.064029        1
296     45.395197   112.092385      96.380218   0.055378        1
408     47.262919   130.213667      86.746395   0.072137        1
433     49.329223   100.777589      91.064328   0.072049        1
694     37.201470   136.702408      97.064101   0.081518        1
860     42.684002   111.637094      88.243460   0.082998        1
1024    45.716582   100.484197      87.468484   0.061929        1
1074    42.300441   132.106146      94.733244   0.086052        1
1084    49.316301   126.733968      87.294705   0.067630        1
1092    41.825875   117.403502      87.217075   0.074976        1
1127    39.891153   159.627367      76.572341   0.091332        1
1153    35.850882   112.270694      99.275092   0.055746        1
1231    38.871274   134.379273      91.152930   0.076597        1
1276    46.700721   112.448901      86.966223   0.082923        1
1354    41.306355   115.784960      88.379756   0.069479        1
1419    39.922689   113.971014      99.457875   0.064443        1
1754    45.968525   132.611028      87.842651   0.059730        1
1781    48.470801   114.966354      91.847859   0.090733        1
1874    37.221121   116.157156      92.356380   0.056151        1

In [10]:
total_records = len(df)

anomaly_count = len(anomalies)

anomaly_rate = anomaly_count / total_records * 100

print(f"Total Records: {total_records}")
print(f"Anomalies: {anomaly_count}")
print(f"Anomaly Rate: {anomaly_rate:.2f}%")

Total Records: 10000
Anomalies: 100
Anomaly Rate: 1.00%